# Generated by Django 5.0.1 on 2024-02-05 08:50

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerStatementRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(blank=True, default='', help_text='First name in english', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', help_text='Last name in english', max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', help_text='Middle name in english', max_length=100)),
                ('status', models.IntegerField(choices=[(2, 'Approved'), (6, 'Cancelled'), (8, 'Waiting confirmation email')], default=8)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_statement_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application for customer registration',
            },
        ),
    ]
