# Generated by Django 5.0.1 on 2024-02-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_securitycode_customerstatementregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstatementregistration',
            name='status',
            field=models.IntegerField(choices=[(2, 'Approved'), (6, 'Cancelled'), (8, 'Waiting confirmation email')]),
        ),
    ]
