# Generated by Django 5.0.1 on 2024-02-05 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Website follow date and time')),
                ('webpage_size', models.IntegerField(help_text='Webpage data size')),
                ('website', models.ForeignKey(help_text='Website to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_history', to='websites.website')),
            ],
            options={
                'verbose_name': 'Website following history',
                'ordering': ['-id'],
            },
        ),
    ]
