# Generated by Django 5.0.1 on 2024-02-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='webpage',
            field=models.TextField(default='', help_text='Full webpage link'),
        ),
    ]
